include theos/makefiles/common.mk

TOOL_NAME = telBookdaemon
telBookdaemon_FILES = main.mm iTestDaemonManager.m
telBookdaemon_FRAMEWORKS = IOKit UIKit Foundation 
telBookdaemon_CFLAGS = 
telBookdaemon_LDFLAGS = #-lactivator -lRCDaemon -L./ 
include $(THEOS_MAKE_PATH)/tool.mk
